// Generated by scripts/sync-buffer-plugin-catalog.py from
// Catalog/buffer-plugins.json. Do not edit this file directly.

enum PresetBufferPluginCatalog {
    static let releaseVersion = "1.1.0"
    static let entries: [PresetBufferPluginCatalogEntry] = [
        PresetBufferPluginCatalogEntry(
            id: "builtin.codex-cli",
            nameZH: "ChatGPT",
            nameEN: "ChatGPT",
            version: "1.1",
            summaryZH: "通过 Codex CLI 使用 ChatGPT 生成内容，可选择模型与推理深度。",
            summaryEN: "Generate with ChatGPT through Codex CLI, with a selectable model and reasoning effort.",
            producerID: "openai",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.claude-code-cli",
            nameZH: "Claude",
            nameEN: "Claude",
            version: "1.1",
            summaryZH: "通过 Claude Code CLI 使用 Claude 生成内容，可选择模型与推理深度。",
            summaryEN: "Generate with Claude through Claude Code CLI, with a selectable model and reasoning effort.",
            producerID: "anthropic",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.openai-compatible",
            nameZH: "AI API",
            nameEN: "AI API",
            version: "1.0",
            summaryZH: "把源缓冲区原样作为请求发给通用 Open API（OpenAI 兼容），回复进入独立目标缓冲区。",
            summaryEN: "Send the source buffer unchanged as a request to an OpenAI-compatible API; the reply lands in an independent target buffer.",
            producerID: "official",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.scholay",
            nameZH: "Reference",
            nameEN: "Reference",
            version: "0.1",
            summaryZH: "检索学术论文，把一个观点改写成带夹注的正文与对应参考文献。",
            summaryEN: "Find academic papers and turn a claim into a cited sentence with matching references.",
            producerID: "scholay",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.polisher",
            nameZH: "Polisher",
            nameEN: "Polisher",
            version: "1.1.0",
            summaryZH: "将输入文字润色或改写为清晰、严谨的学术语言，保留原意。",
            summaryEN: "Polish or rewrite input in clear academic language while preserving its meaning.",
            producerID: "scholay",
            defaultInstalled: false,
            defaultEnabled: false,
            downloadAssetName: "preset-plugin-builtin.polisher-1.1.0.json",
            sha256: "4c09e8ae9e04f06faa611410199d1b18b0c3a016eb1de38b1cc68fdd4f20bfb5"
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.latex",
            nameZH: "LaTeX",
            nameEN: "LaTeX",
            version: "1.1.0",
            summaryZH: "把公式图片或自然语言说明转换为可复制的 LaTeX 公式。",
            summaryEN: "Convert a formula image or natural-language description into copyable LaTeX.",
            producerID: "scholay",
            defaultInstalled: false,
            defaultEnabled: false,
            downloadAssetName: "preset-plugin-builtin.latex-1.1.0.json",
            sha256: "f6daa0386c48b72f8793c971ea4d6c79ca7ad31b9f39603d03b35cc10f369c2a"
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.apple-translation",
            nameZH: "实时翻译",
            nameEN: "Real-time Translation",
            version: "2.2",
            summaryZH: "用 Apple 本地翻译把源缓冲区实时翻译到独立目标缓冲区，原文不离开本机。",
            summaryEN: "Translate the source buffer into an independent target buffer with Apple on-device translation; the text never leaves this Mac.",
            producerID: "official",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.stream-input",
            nameZH: "意识流输入",
            nameEN: "Stream of Consciousness Input",
            version: "1.4",
            summaryZH: "连续输入全拼，由本地 Rime + Octagram 模块低延迟解码，复杂输入再回退到独立 AI 渠道，并给出 1–5 个完整候选。",
            summaryEN: "Decode continuous full Pinyin with a low-latency local Rime + Octagram module, falling back to the independent AI connector for complex input and returning one to five complete guesses.",
            producerID: "official",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.music",
            nameZH: "电音演奏",
            nameEN: "Electronic Music",
            version: "0.2.3",
            summaryZH: "用 AudioKit 演奏四弦贝斯排列的 40 键电音，搭配真实采样架子鼓、八种加花和两轨 Loop；演奏键仅在音乐面板获焦时生效。",
            summaryEN: "Play 40 electronic notes in a four-string bass layout with AudioKit, a sampled acoustic drum kit, eight fills and two loop tracks. Performance keys are scoped to the focused music panel.",
            producerID: "official",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.morse",
            nameZH: "摩斯电码",
            nameEN: "Morse Code",
            version: "0.1.0",
            summaryZH: "用空格键拍发摩斯电码：短按为点、长按为划，停顿即成字母，带侧音与解码提示音；上方显示映射槽、待组合槽与走纸线，下方输出英文。",
            summaryEN: "Key Morse code with the Space bar: a short press is a dot, a long press a dash, and a pause completes the letter, with a sidetone and decode chimes. The upper rail shows the mapping and combine slots and a sweeping line; decoded English appears below.",
            producerID: "official",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
    ]

    static func entry(id: String) -> PresetBufferPluginCatalogEntry? {
        entries.first { $0.id == id }
    }
}
